### PR TITLE
Test with AppVeyor

### PR DESCRIPTION
**Pull request by talex5**

### CODE REVIEW

**Comment by talex5** [comment]
Note, this fails for me with:

```
#=== ERROR while compiling sha.1.10 ===========================================#
# opam-version         1.3.0~dev (2c2399d98ad0ebcb43a4bc856f3636030bb376db)
# os                   win32
# command              make
# path                 C:/cygwin64/home/appveyor/.opam/4.03.0+mingw64c/build/sha.1.10
# exit-code            2
# env-file             C:/cygwin64/home/appveyor/.opam/4.03.0+mingw64c/build/sha.1.10\sha-288-d2c37b.env
# stdout-file          C:/cygwin64/home/appveyor/.opam/4.03.0+mingw64c/build/sha.1.10\sha-288-d2c37b.out
# stderr-file          C:/cygwin64/home/appveyor/.opam/4.03.0+mingw64c/build/sha.1.10\sha-288-d2c37b.err
### stdout ###
# ocamlc -c -o sha1.cmi sha1.mli
# ocamlc -ccopt "-Wall -O3 -funroll-loops -I/usr/include" -c -o sha1.o sha1.c
### stderr ###
# [...]
# /usr/include/sys/_timeval.h:40:18: error: conflicting types for ‘time_t’
#  typedef _TIME_T_ time_t;
#                   ^~~~~~
# In file included from /usr/x86_64-w64-mingw32/sys-root/mingw/include/stddef.h:7:0,
#                  from /usr/lib/gcc/x86_64-w64-mingw32/6.4.0/include/stddef.h:1,
#                  from /usr/include/sys/reent.h:14,
#                  from /usr/include/string.h:11,
#                  from sha1.c:16:
# /usr/x86_64-w64-mingw32/sys-root/mingw/include/crtdefs.h:138:20: note: previous declaration of ‘time_t’ was here
#  typedef __time64_t time_t;
#                     ^~~~~~
# make: *** [Makefile:94: sha1.o] Error 2
```

Meanwhile, 0install (which has tested sha with AppVeyor as a dependency for a long time) has just started failing with:

```
#=== ERROR while compiling sha.1.10 ===========================================#
# opam-version         1.3.0~dev (2c2399d98ad0ebcb43a4bc856f3636030bb376db)
# os                   win32
# command              make
# path                 C:/cygwin64/home/appveyor/.opam/4.03.0+mingw64c/build/sha.1.10
# exit-code            2
# env-file             C:/cygwin64/home/appveyor/.opam/4.03.0+mingw64c/build/sha.1.10\sha-288-4197d2.env
# stdout-file          C:/cygwin64/home/appveyor/.opam/4.03.0+mingw64c/build/sha.1.10\sha-288-4197d2.out
# stderr-file          C:/cygwin64/home/appveyor/.opam/4.03.0+mingw64c/build/sha.1.10\sha-288-4197d2.err
### stdout ###
# ocamlc -I  -c -o sha1.cmi sha1.mli
# ocamlc -ccopt "-Wall -O3 -funroll-loops" -c -o sha1.o sha1.c
# mv sha1.o sha1.lib.o
# ocamlc -ccopt "-Wall -O3 -funroll-loops" -c -o sha1_stubs.o sha1_stubs.c
# ocamlc -I  -c -o sha1.cmo sha1.ml
### stderr ###
# ocamlfind: Package `oUnit' not found
# ocamlfind: Package `oUnit' not found
# File "sha1.ml", line 1:
# Error: The output file sha1.cmo has the wrong name. The extension implies an object file but the link step was requested
# make: *** [Makefile:87: sha1.cmo] Error 2
```

**Comment by talex5** [comment]
Also, Travis is now failing with:
```
$ bash ./.travis-docker.sh
prepare.ci
Sending build context to Docker daemon 226.3 kB
Step 1/6 : FROM ocaml/opam:alpine_ocaml-4.02.0
manifest for ocaml/opam:alpine_ocaml-4.02.0 not found
```

**Comment by talex5** [comment]
(this code is copied from https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/appveyor.yml, which doesn't specify a license - I've filed an issue at https://github.com/ocaml/ocaml-ci-scripts/issues/201, but I doubt it will be a problem)

**Comment by djs55** [comment]
I've enabled appveyor on this repo and rebased your branch to see what happens.

**Comment by talex5** [comment]
Same problem. I wonder if the `-I/usr/include` at the top of the Makefile is the problem. Git says it was added in 6550b3528c90859d519f2b74391bc606553289c6, but I'm not sure why.

I've pushed a new commit to try removing it...

**Comment by talex5** [comment]
Well, that got a few more lines, but:

```
# In file included from sha1.c:19:0:
# bitfn.h:71:20: fatal error: endian.h: No such file or directory
#  #include <endian.h>
#                     ^
# compilation terminated.
```

Probably someone with a Windows machine will have to debug this.

**Comment by djs55** [comment]
Travis and appveyor are green -- I'll merge this for the release.

**Comment by nojb** [comment]
Note that this fixes compilation for the `mingw` toolchain; `msvc` compilation still needs some more work. I will try to put together a PR.

**Comment by talex5** [comment]
Just to add to the confusion, I see there's another patch to support Windows (from @fdopen) at https://github.com/fdopen/opam-repository-mingw/commit/cd2ebee812c4b1599abbe808c65d2061efb90756#diff-fe866ea31ff1e66dce52f6124adbeacd.

**Pull request merged**
