### PR TITLE
Update CHANGES.md for 1.13

### PR DESCRIPTION
**Pull request by djs55**
Signed-off-by: David Scott <dave@recoil.org>

### CODE REVIEW

**Comment by XVilka** [comment]
Isn't this a good time to merge?

**Comment by XVilka** [comment]
Note, the failing appveyor was fixed, so it will be green next push https://github.com/ocaml/ocaml-ci-scripts/commit/03545c96ed3836af157acae570b0fec359962bd0

**Comment by XVilka** [comment]
A gentle ping.

**Comment by djs55** [comment]
Appveyor is indeed fixed, so merging!

**Pull request merged**
