### PR TITLE
Do not export unnecessary symbols + port to dune + Windows fixes

### PR DESCRIPTION
**Pull request by nojb**
Hello!

I made a number of small fixes to `ocaml-sha` which you may be interested in integrating:

1. it turns out that some of the symbols in `sha{1,256,512}c.c` clash with symbols [exported](https://github.com/johnwhitington/camlpdf/blob/db92b4f6cb0dc597040885f67a1af1c5a86f4bde/sha2.h#L82-L84) by `camlpdf`, which makes it impossible to link both together. To work around this issue I inline `sha{1,256,512}c.c` inside the header `sha{1,256,512}.h` and declare all functions to be static. The files are small enough that this is not too messy.

2. Port to dune from jbuilder

3. Some Windows fixes which allow to compile on Windows out-of-the-box.

Thanks!

### CODE REVIEW

**Comment by XVilka** [comment]
With dune 2.0 integration sha blocks dune upgrade by depending on jbuilder.transition. So merging this PR is very important.

**Comment by XVilka** [comment]
Could you please fix the opam file too?
```
+ opam lint -
[WARNING] Failed checks on sha package definition from source at file:///tmp/opam-ci-192:
             error 57: Synopsis and description must not be both empty
Errors.
             error 57: Synopsis and description must not be both empty
'unset TESTS; OPAMYES=1 export OPAMYES; set -uex; cp sha.opam /tmp/opam-ci-192 && opam show /tmp/opam-ci-192 --raw | opam lint -' exited 1. Terminating with 1
The command "bash ./.travis-docker.sh" exited with 1.
```
@djs55 ping?

**Comment by nojb** [comment]
> Could you please fix the opam file too?

Fixed, thanks.

**Comment by XVilka** [comment]
Still missing the description or synopsis though.

**Comment by andyli** [comment]
Can this be prioritized? The latest version of dune gives error for jbuilder projects.

> Error: jbuild files are no longer supported, please convert this file to a
dune file instead.
Note: You can use "dune upgrade" to convert your project to dune.

**Comment by djs55** [comment]
Thanks and sorry for the delay. I'll merge this and see what else needs to be done before a release.

**Pull request merged**
